

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 

  flutter-build:
    name: Flutter Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      



        
